import type { Exercise } from "./model";
export const catalog: Exercise[] = [
  {
    id: "barbell-bench-press",
    name: "Barbell bench press",
    aliases: ["bench"],
    muscle: "Chest",
    secondary: ["Triceps", "Shoulders"],
    equipment: "Barbell",
    pattern: "press",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your torso and keep your shoulders stable. Lower the load with control, then press without bouncing.",
    ],
    cues: "Keep wrists aligned and use a comfortable range.",
  },
  {
    id: "incline-barbell-bench-press",
    name: "Incline barbell bench press",
    aliases: [],
    muscle: "Chest",
    secondary: ["Triceps", "Shoulders"],
    equipment: "Barbell",
    pattern: "press",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your torso and keep your shoulders stable. Lower the load with control, then press without bouncing.",
    ],
    cues: "Keep wrists aligned and use a comfortable range.",
  },
  {
    id: "dumbbell-bench-press",
    name: "Dumbbell bench press",
    aliases: [],
    muscle: "Chest",
    secondary: ["Triceps", "Shoulders"],
    equipment: "Dumbbell",
    pattern: "press",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your torso and keep your shoulders stable. Lower the load with control, then press without bouncing.",
    ],
    cues: "Keep wrists aligned and use a comfortable range.",
  },
  {
    id: "incline-dumbbell-bench-press",
    name: "Incline dumbbell bench press",
    aliases: [],
    muscle: "Chest",
    secondary: ["Triceps", "Shoulders"],
    equipment: "Dumbbell",
    pattern: "press",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your torso and keep your shoulders stable. Lower the load with control, then press without bouncing.",
    ],
    cues: "Keep wrists aligned and use a comfortable range.",
  },
  {
    id: "dumbbell-floor-press",
    name: "Dumbbell floor press",
    aliases: [],
    muscle: "Chest",
    secondary: ["Triceps", "Shoulders"],
    equipment: "Dumbbell",
    pattern: "press",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your torso and keep your shoulders stable. Lower the load with control, then press without bouncing.",
    ],
    cues: "Keep wrists aligned and use a comfortable range.",
  },
  {
    id: "machine-chest-press",
    name: "Machine chest press",
    aliases: [],
    muscle: "Chest",
    secondary: ["Triceps", "Shoulders"],
    equipment: "Machine",
    pattern: "press",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your torso and keep your shoulders stable. Lower the load with control, then press without bouncing.",
    ],
    cues: "Keep wrists aligned and use a comfortable range.",
  },
  {
    id: "smith-machine-bench-press",
    name: "Smith machine bench press",
    aliases: [],
    muscle: "Chest",
    secondary: ["Triceps", "Shoulders"],
    equipment: "Smith machine",
    pattern: "press",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your torso and keep your shoulders stable. Lower the load with control, then press without bouncing.",
    ],
    cues: "Keep wrists aligned and use a comfortable range.",
  },
  {
    id: "smith-machine-incline-press",
    name: "Smith machine incline press",
    aliases: [],
    muscle: "Chest",
    secondary: ["Triceps", "Shoulders"],
    equipment: "Smith machine",
    pattern: "press",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your torso and keep your shoulders stable. Lower the load with control, then press without bouncing.",
    ],
    cues: "Keep wrists aligned and use a comfortable range.",
  },
  {
    id: "push-up",
    name: "Push-up",
    aliases: [],
    muscle: "Chest",
    secondary: ["Triceps", "Shoulders"],
    equipment: "Bodyweight",
    pattern: "press",
    metric: "reps",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your torso and keep your shoulders stable. Lower the load with control, then press without bouncing.",
    ],
    cues: "Keep wrists aligned and use a comfortable range.",
  },
  {
    id: "incline-push-up",
    name: "Incline push-up",
    aliases: [],
    muscle: "Chest",
    secondary: ["Triceps", "Shoulders"],
    equipment: "Bodyweight",
    pattern: "press",
    metric: "reps",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your torso and keep your shoulders stable. Lower the load with control, then press without bouncing.",
    ],
    cues: "Keep wrists aligned and use a comfortable range.",
  },
  {
    id: "knee-push-up",
    name: "Knee push-up",
    aliases: [],
    muscle: "Chest",
    secondary: ["Triceps", "Shoulders"],
    equipment: "Bodyweight",
    pattern: "press",
    metric: "reps",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your torso and keep your shoulders stable. Lower the load with control, then press without bouncing.",
    ],
    cues: "Keep wrists aligned and use a comfortable range.",
  },
  {
    id: "close-grip-push-up",
    name: "Close-grip push-up",
    aliases: [],
    muscle: "Chest",
    secondary: ["Triceps", "Shoulders"],
    equipment: "Bodyweight",
    pattern: "press",
    metric: "reps",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your torso and keep your shoulders stable. Lower the load with control, then press without bouncing.",
    ],
    cues: "Keep wrists aligned and use a comfortable range.",
  },
  {
    id: "cable-chest-fly",
    name: "Cable chest fly",
    aliases: [],
    muscle: "Chest",
    secondary: ["Triceps", "Shoulders"],
    equipment: "Cable",
    pattern: "fly",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "With a slight bend in your elbows, bring your arms together in front of your chest. Return slowly without stretching beyond comfort.",
    ],
    cues: "Keep the elbow angle steady; avoid excessive depth.",
  },
  {
    id: "low-to-high-cable-fly",
    name: "Low-to-high cable fly",
    aliases: [],
    muscle: "Chest",
    secondary: ["Triceps", "Shoulders"],
    equipment: "Cable",
    pattern: "fly",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "With a slight bend in your elbows, bring your arms together in front of your chest. Return slowly without stretching beyond comfort.",
    ],
    cues: "Keep the elbow angle steady; avoid excessive depth.",
  },
  {
    id: "high-to-low-cable-fly",
    name: "High-to-low cable fly",
    aliases: [],
    muscle: "Chest",
    secondary: ["Triceps", "Shoulders"],
    equipment: "Cable",
    pattern: "fly",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "With a slight bend in your elbows, bring your arms together in front of your chest. Return slowly without stretching beyond comfort.",
    ],
    cues: "Keep the elbow angle steady; avoid excessive depth.",
  },
  {
    id: "pec-deck-fly",
    name: "Pec deck fly",
    aliases: [],
    muscle: "Chest",
    secondary: ["Triceps", "Shoulders"],
    equipment: "Machine",
    pattern: "fly",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "With a slight bend in your elbows, bring your arms together in front of your chest. Return slowly without stretching beyond comfort.",
    ],
    cues: "Keep the elbow angle steady; avoid excessive depth.",
  },
  {
    id: "dumbbell-chest-fly",
    name: "Dumbbell chest fly",
    aliases: [],
    muscle: "Chest",
    secondary: ["Triceps", "Shoulders"],
    equipment: "Dumbbell",
    pattern: "fly",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "With a slight bend in your elbows, bring your arms together in front of your chest. Return slowly without stretching beyond comfort.",
    ],
    cues: "Keep the elbow angle steady; avoid excessive depth.",
  },
  {
    id: "bent-over-barbell-row",
    name: "Bent-over barbell row",
    aliases: [],
    muscle: "Back",
    secondary: ["Biceps"],
    equipment: "Barbell",
    pattern: "row",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your trunk. Pull the handle or load toward your torso, letting your shoulder blades move naturally. Lower with control.",
    ],
    cues: "Avoid jerking or shrugging; keep your neck relaxed.",
  },
  {
    id: "pendlay-row",
    name: "Pendlay row",
    aliases: [],
    muscle: "Back",
    secondary: ["Biceps"],
    equipment: "Barbell",
    pattern: "row",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your trunk. Pull the handle or load toward your torso, letting your shoulder blades move naturally. Lower with control.",
    ],
    cues: "Avoid jerking or shrugging; keep your neck relaxed.",
  },
  {
    id: "one-arm-dumbbell-row",
    name: "One-arm dumbbell row",
    aliases: [],
    muscle: "Back",
    secondary: ["Biceps"],
    equipment: "Dumbbell",
    pattern: "row",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your trunk. Pull the handle or load toward your torso, letting your shoulder blades move naturally. Lower with control.",
    ],
    cues: "Avoid jerking or shrugging; keep your neck relaxed.",
  },
  {
    id: "chest-supported-dumbbell-row",
    name: "Chest-supported dumbbell row",
    aliases: [],
    muscle: "Back",
    secondary: ["Biceps"],
    equipment: "Dumbbell",
    pattern: "row",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your trunk. Pull the handle or load toward your torso, letting your shoulder blades move naturally. Lower with control.",
    ],
    cues: "Avoid jerking or shrugging; keep your neck relaxed.",
  },
  {
    id: "seated-cable-row",
    name: "Seated cable row",
    aliases: [],
    muscle: "Back",
    secondary: ["Biceps"],
    equipment: "Cable",
    pattern: "row",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your trunk. Pull the handle or load toward your torso, letting your shoulder blades move naturally. Lower with control.",
    ],
    cues: "Avoid jerking or shrugging; keep your neck relaxed.",
  },
  {
    id: "wide-grip-cable-row",
    name: "Wide-grip cable row",
    aliases: [],
    muscle: "Back",
    secondary: ["Biceps"],
    equipment: "Cable",
    pattern: "row",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your trunk. Pull the handle or load toward your torso, letting your shoulder blades move naturally. Lower with control.",
    ],
    cues: "Avoid jerking or shrugging; keep your neck relaxed.",
  },
  {
    id: "single-arm-cable-row",
    name: "Single-arm cable row",
    aliases: [],
    muscle: "Back",
    secondary: ["Biceps"],
    equipment: "Cable",
    pattern: "row",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your trunk. Pull the handle or load toward your torso, letting your shoulder blades move naturally. Lower with control.",
    ],
    cues: "Avoid jerking or shrugging; keep your neck relaxed.",
  },
  {
    id: "machine-seated-row",
    name: "Machine seated row",
    aliases: [],
    muscle: "Back",
    secondary: ["Biceps"],
    equipment: "Machine",
    pattern: "row",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your trunk. Pull the handle or load toward your torso, letting your shoulder blades move naturally. Lower with control.",
    ],
    cues: "Avoid jerking or shrugging; keep your neck relaxed.",
  },
  {
    id: "t-bar-row",
    name: "T-bar row",
    aliases: [],
    muscle: "Back",
    secondary: ["Biceps"],
    equipment: "Machine",
    pattern: "row",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your trunk. Pull the handle or load toward your torso, letting your shoulder blades move naturally. Lower with control.",
    ],
    cues: "Avoid jerking or shrugging; keep your neck relaxed.",
  },
  {
    id: "inverted-row",
    name: "Inverted row",
    aliases: [],
    muscle: "Back",
    secondary: ["Biceps"],
    equipment: "Bodyweight",
    pattern: "row",
    metric: "reps",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your trunk. Pull the handle or load toward your torso, letting your shoulder blades move naturally. Lower with control.",
    ],
    cues: "Avoid jerking or shrugging; keep your neck relaxed.",
  },
  {
    id: "resistance-band-row",
    name: "Resistance band row",
    aliases: [],
    muscle: "Back",
    secondary: ["Biceps"],
    equipment: "Band",
    pattern: "row",
    metric: "reps",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your trunk. Pull the handle or load toward your torso, letting your shoulder blades move naturally. Lower with control.",
    ],
    cues: "Avoid jerking or shrugging; keep your neck relaxed.",
  },
  {
    id: "lat-pulldown",
    name: "Lat pulldown",
    aliases: [],
    muscle: "Back",
    secondary: ["Biceps"],
    equipment: "Cable",
    pattern: "pull",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Start with arms extended comfortably. Pull toward the upper chest or bring your body toward the bar. Return with control.",
    ],
    cues: "Keep shoulders comfortable; do not pull behind the neck.",
  },
  {
    id: "close-grip-lat-pulldown",
    name: "Close-grip lat pulldown",
    aliases: [],
    muscle: "Back",
    secondary: ["Biceps"],
    equipment: "Cable",
    pattern: "pull",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Start with arms extended comfortably. Pull toward the upper chest or bring your body toward the bar. Return with control.",
    ],
    cues: "Keep shoulders comfortable; do not pull behind the neck.",
  },
  {
    id: "wide-grip-lat-pulldown",
    name: "Wide-grip lat pulldown",
    aliases: [],
    muscle: "Back",
    secondary: ["Biceps"],
    equipment: "Cable",
    pattern: "pull",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Start with arms extended comfortably. Pull toward the upper chest or bring your body toward the bar. Return with control.",
    ],
    cues: "Keep shoulders comfortable; do not pull behind the neck.",
  },
  {
    id: "single-arm-lat-pulldown",
    name: "Single-arm lat pulldown",
    aliases: [],
    muscle: "Back",
    secondary: ["Biceps"],
    equipment: "Cable",
    pattern: "pull",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Start with arms extended comfortably. Pull toward the upper chest or bring your body toward the bar. Return with control.",
    ],
    cues: "Keep shoulders comfortable; do not pull behind the neck.",
  },
  {
    id: "pull-up",
    name: "Pull-up",
    aliases: [],
    muscle: "Back",
    secondary: ["Biceps"],
    equipment: "Bodyweight",
    pattern: "pull",
    metric: "reps",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Start with arms extended comfortably. Pull toward the upper chest or bring your body toward the bar. Return with control.",
    ],
    cues: "Keep shoulders comfortable; do not pull behind the neck.",
  },
  {
    id: "chin-up",
    name: "Chin-up",
    aliases: [],
    muscle: "Back",
    secondary: ["Biceps"],
    equipment: "Bodyweight",
    pattern: "pull",
    metric: "reps",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Start with arms extended comfortably. Pull toward the upper chest or bring your body toward the bar. Return with control.",
    ],
    cues: "Keep shoulders comfortable; do not pull behind the neck.",
  },
  {
    id: "assisted-pull-up",
    name: "Assisted pull-up",
    aliases: [],
    muscle: "Back",
    secondary: ["Biceps"],
    equipment: "Machine",
    pattern: "pull",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Start with arms extended comfortably. Pull toward the upper chest or bring your body toward the bar. Return with control.",
    ],
    cues: "Keep shoulders comfortable; do not pull behind the neck.",
  },
  {
    id: "straight-arm-cable-pulldown",
    name: "Straight-arm cable pulldown",
    aliases: [],
    muscle: "Back",
    secondary: ["Biceps"],
    equipment: "Cable",
    pattern: "pull",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Start with arms extended comfortably. Pull toward the upper chest or bring your body toward the bar. Return with control.",
    ],
    cues: "Keep shoulders comfortable; do not pull behind the neck.",
  },
  {
    id: "barbell-back-squat",
    name: "Barbell back squat",
    aliases: [],
    muscle: "Legs",
    secondary: ["Glutes"],
    equipment: "Barbell",
    pattern: "squat",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace and bend at the hips and knees, tracking knees with toes. Descend through a comfortable range and push back up.",
    ],
    cues: "Keep your feet stable; use safety stops for loaded squats.",
  },
  {
    id: "barbell-front-squat",
    name: "Barbell front squat",
    aliases: [],
    muscle: "Legs",
    secondary: ["Glutes"],
    equipment: "Barbell",
    pattern: "squat",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace and bend at the hips and knees, tracking knees with toes. Descend through a comfortable range and push back up.",
    ],
    cues: "Keep your feet stable; use safety stops for loaded squats.",
  },
  {
    id: "goblet-squat",
    name: "Goblet squat",
    aliases: [],
    muscle: "Legs",
    secondary: ["Glutes"],
    equipment: "Dumbbell",
    pattern: "squat",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace and bend at the hips and knees, tracking knees with toes. Descend through a comfortable range and push back up.",
    ],
    cues: "Keep your feet stable; use safety stops for loaded squats.",
  },
  {
    id: "bodyweight-squat",
    name: "Bodyweight squat",
    aliases: [],
    muscle: "Legs",
    secondary: ["Glutes"],
    equipment: "Bodyweight",
    pattern: "squat",
    metric: "reps",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace and bend at the hips and knees, tracking knees with toes. Descend through a comfortable range and push back up.",
    ],
    cues: "Keep your feet stable; use safety stops for loaded squats.",
  },
  {
    id: "smith-machine-squat",
    name: "Smith machine squat",
    aliases: [],
    muscle: "Legs",
    secondary: ["Glutes"],
    equipment: "Smith machine",
    pattern: "squat",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace and bend at the hips and knees, tracking knees with toes. Descend through a comfortable range and push back up.",
    ],
    cues: "Keep your feet stable; use safety stops for loaded squats.",
  },
  {
    id: "hack-squat",
    name: "Hack squat",
    aliases: [],
    muscle: "Legs",
    secondary: ["Glutes"],
    equipment: "Machine",
    pattern: "squat",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace and bend at the hips and knees, tracking knees with toes. Descend through a comfortable range and push back up.",
    ],
    cues: "Keep your feet stable; use safety stops for loaded squats.",
  },
  {
    id: "seated-leg-press",
    name: "Seated leg press",
    aliases: ["legpress"],
    muscle: "Legs",
    secondary: ["Glutes"],
    equipment: "Machine",
    pattern: "squat",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace and bend at the hips and knees, tracking knees with toes. Descend through a comfortable range and push back up.",
    ],
    cues: "Keep your feet stable; use safety stops for loaded squats.",
  },
  {
    id: "45-degree-leg-press",
    name: "45-degree leg press",
    aliases: [],
    muscle: "Legs",
    secondary: ["Glutes"],
    equipment: "Machine",
    pattern: "squat",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace and bend at the hips and knees, tracking knees with toes. Descend through a comfortable range and push back up.",
    ],
    cues: "Keep your feet stable; use safety stops for loaded squats.",
  },
  {
    id: "belt-squat",
    name: "Belt squat",
    aliases: [],
    muscle: "Legs",
    secondary: ["Glutes"],
    equipment: "Machine",
    pattern: "squat",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace and bend at the hips and knees, tracking knees with toes. Descend through a comfortable range and push back up.",
    ],
    cues: "Keep your feet stable; use safety stops for loaded squats.",
  },
  {
    id: "conventional-deadlift",
    name: "Conventional deadlift",
    aliases: ["dead lift", "deadlift"],
    muscle: "Glutes",
    secondary: ["Legs"],
    equipment: "Barbell",
    pattern: "hinge",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your trunk and move your hips back while keeping the load close. Extend your hips to stand; avoid leaning back at the top.",
    ],
    cues: "Maintain a controlled spine position and stable feet.",
  },
  {
    id: "sumo-deadlift",
    name: "Sumo deadlift",
    aliases: [],
    muscle: "Glutes",
    secondary: ["Legs"],
    equipment: "Barbell",
    pattern: "hinge",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your trunk and move your hips back while keeping the load close. Extend your hips to stand; avoid leaning back at the top.",
    ],
    cues: "Maintain a controlled spine position and stable feet.",
  },
  {
    id: "romanian-deadlift",
    name: "Romanian deadlift",
    aliases: [],
    muscle: "Glutes",
    secondary: ["Legs"],
    equipment: "Barbell",
    pattern: "hinge",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your trunk and move your hips back while keeping the load close. Extend your hips to stand; avoid leaning back at the top.",
    ],
    cues: "Maintain a controlled spine position and stable feet.",
  },
  {
    id: "dumbbell-romanian-deadlift",
    name: "Dumbbell Romanian deadlift",
    aliases: [],
    muscle: "Glutes",
    secondary: ["Legs"],
    equipment: "Dumbbell",
    pattern: "hinge",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your trunk and move your hips back while keeping the load close. Extend your hips to stand; avoid leaning back at the top.",
    ],
    cues: "Maintain a controlled spine position and stable feet.",
  },
  {
    id: "single-leg-romanian-deadlift",
    name: "Single-leg Romanian deadlift",
    aliases: [],
    muscle: "Glutes",
    secondary: ["Legs"],
    equipment: "Dumbbell",
    pattern: "hinge",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your trunk and move your hips back while keeping the load close. Extend your hips to stand; avoid leaning back at the top.",
    ],
    cues: "Maintain a controlled spine position and stable feet.",
  },
  {
    id: "kettlebell-deadlift",
    name: "Kettlebell deadlift",
    aliases: [],
    muscle: "Glutes",
    secondary: ["Legs"],
    equipment: "Kettlebell",
    pattern: "hinge",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your trunk and move your hips back while keeping the load close. Extend your hips to stand; avoid leaning back at the top.",
    ],
    cues: "Maintain a controlled spine position and stable feet.",
  },
  {
    id: "cable-pull-through",
    name: "Cable pull-through",
    aliases: [],
    muscle: "Glutes",
    secondary: ["Legs"],
    equipment: "Cable",
    pattern: "hinge",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your trunk and move your hips back while keeping the load close. Extend your hips to stand; avoid leaning back at the top.",
    ],
    cues: "Maintain a controlled spine position and stable feet.",
  },
  {
    id: "dumbbell-reverse-lunge",
    name: "Dumbbell reverse lunge",
    aliases: [],
    muscle: "Legs",
    secondary: ["Glutes"],
    equipment: "Dumbbell",
    pattern: "lunge",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Take a stable split stance or step as directed. Bend both knees through a comfortable range, then press through the supporting foot.",
    ],
    cues: "Use support if balance limits control.",
  },
  {
    id: "dumbbell-walking-lunge",
    name: "Dumbbell walking lunge",
    aliases: [],
    muscle: "Legs",
    secondary: ["Glutes"],
    equipment: "Dumbbell",
    pattern: "lunge",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Take a stable split stance or step as directed. Bend both knees through a comfortable range, then press through the supporting foot.",
    ],
    cues: "Use support if balance limits control.",
  },
  {
    id: "bodyweight-reverse-lunge",
    name: "Bodyweight reverse lunge",
    aliases: [],
    muscle: "Legs",
    secondary: ["Glutes"],
    equipment: "Bodyweight",
    pattern: "lunge",
    metric: "reps",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Take a stable split stance or step as directed. Bend both knees through a comfortable range, then press through the supporting foot.",
    ],
    cues: "Use support if balance limits control.",
  },
  {
    id: "bulgarian-split-squat",
    name: "Bulgarian split squat",
    aliases: [],
    muscle: "Legs",
    secondary: ["Glutes"],
    equipment: "Dumbbell",
    pattern: "lunge",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Take a stable split stance or step as directed. Bend both knees through a comfortable range, then press through the supporting foot.",
    ],
    cues: "Use support if balance limits control.",
  },
  {
    id: "dumbbell-step-up",
    name: "Dumbbell step-up",
    aliases: [],
    muscle: "Legs",
    secondary: ["Glutes"],
    equipment: "Dumbbell",
    pattern: "lunge",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Take a stable split stance or step as directed. Bend both knees through a comfortable range, then press through the supporting foot.",
    ],
    cues: "Use support if balance limits control.",
  },
  {
    id: "bodyweight-step-up",
    name: "Bodyweight step-up",
    aliases: [],
    muscle: "Legs",
    secondary: ["Glutes"],
    equipment: "Bodyweight",
    pattern: "lunge",
    metric: "reps",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Take a stable split stance or step as directed. Bend both knees through a comfortable range, then press through the supporting foot.",
    ],
    cues: "Use support if balance limits control.",
  },
  {
    id: "lateral-lunge",
    name: "Lateral lunge",
    aliases: [],
    muscle: "Legs",
    secondary: ["Glutes"],
    equipment: "Bodyweight",
    pattern: "lunge",
    metric: "reps",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Take a stable split stance or step as directed. Bend both knees through a comfortable range, then press through the supporting foot.",
    ],
    cues: "Use support if balance limits control.",
  },
  {
    id: "leg-extension",
    name: "Leg extension",
    aliases: [],
    muscle: "Legs",
    secondary: ["Glutes"],
    equipment: "Machine",
    pattern: "extension",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Adjust the machine so its pivot aligns with your knee. Extend the knees smoothly, then return the padded lever with control.",
    ],
    cues: "Avoid swinging or snapping the knees straight.",
  },
  {
    id: "single-leg-extension",
    name: "Single-leg extension",
    aliases: [],
    muscle: "Legs",
    secondary: ["Glutes"],
    equipment: "Machine",
    pattern: "extension",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Adjust the machine so its pivot aligns with your knee. Extend the knees smoothly, then return the padded lever with control.",
    ],
    cues: "Avoid swinging or snapping the knees straight.",
  },
  {
    id: "seated-leg-curl",
    name: "Seated leg curl",
    aliases: [],
    muscle: "Legs",
    secondary: ["Glutes"],
    equipment: "Machine",
    pattern: "curl",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Adjust the machine to fit your knee position. Bend the knees against the pad and slowly return to the starting position.",
    ],
    cues: "Keep hips stable and move without bouncing.",
  },
  {
    id: "lying-leg-curl",
    name: "Lying leg curl",
    aliases: [],
    muscle: "Legs",
    secondary: ["Glutes"],
    equipment: "Machine",
    pattern: "curl",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Adjust the machine to fit your knee position. Bend the knees against the pad and slowly return to the starting position.",
    ],
    cues: "Keep hips stable and move without bouncing.",
  },
  {
    id: "standing-leg-curl",
    name: "Standing leg curl",
    aliases: [],
    muscle: "Legs",
    secondary: ["Glutes"],
    equipment: "Machine",
    pattern: "curl",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Adjust the machine to fit your knee position. Bend the knees against the pad and slowly return to the starting position.",
    ],
    cues: "Keep hips stable and move without bouncing.",
  },
  {
    id: "barbell-hip-thrust",
    name: "Barbell hip thrust",
    aliases: [],
    muscle: "Glutes",
    secondary: ["Legs"],
    equipment: "Barbell",
    pattern: "hip extension",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Set a stable position with shoulders or upper back supported as needed. Extend the hips, pause briefly and lower with control.",
    ],
    cues: "Keep ribs down; do not arch the lower back to gain height.",
  },
  {
    id: "dumbbell-hip-thrust",
    name: "Dumbbell hip thrust",
    aliases: [],
    muscle: "Glutes",
    secondary: ["Legs"],
    equipment: "Dumbbell",
    pattern: "hip extension",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Set a stable position with shoulders or upper back supported as needed. Extend the hips, pause briefly and lower with control.",
    ],
    cues: "Keep ribs down; do not arch the lower back to gain height.",
  },
  {
    id: "glute-bridge",
    name: "Glute bridge",
    aliases: [],
    muscle: "Glutes",
    secondary: ["Legs"],
    equipment: "Bodyweight",
    pattern: "hip extension",
    metric: "reps",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Set a stable position with shoulders or upper back supported as needed. Extend the hips, pause briefly and lower with control.",
    ],
    cues: "Keep ribs down; do not arch the lower back to gain height.",
  },
  {
    id: "cable-glute-kickback",
    name: "Cable glute kickback",
    aliases: [],
    muscle: "Glutes",
    secondary: ["Legs"],
    equipment: "Cable",
    pattern: "hip extension",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Set a stable position with shoulders or upper back supported as needed. Extend the hips, pause briefly and lower with control.",
    ],
    cues: "Keep ribs down; do not arch the lower back to gain height.",
  },
  {
    id: "machine-hip-thrust",
    name: "Machine hip thrust",
    aliases: [],
    muscle: "Glutes",
    secondary: ["Legs"],
    equipment: "Machine",
    pattern: "hip extension",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Set a stable position with shoulders or upper back supported as needed. Extend the hips, pause briefly and lower with control.",
    ],
    cues: "Keep ribs down; do not arch the lower back to gain height.",
  },
  {
    id: "seated-hip-abduction",
    name: "Seated hip abduction",
    aliases: [],
    muscle: "Glutes",
    secondary: ["Legs"],
    equipment: "Machine",
    pattern: "abduction",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Use a stable seated or standing position. Move the leg or knees outward against resistance, then return slowly.",
    ],
    cues: "Avoid rotating the pelvis or jerking the load.",
  },
  {
    id: "cable-hip-abduction",
    name: "Cable hip abduction",
    aliases: [],
    muscle: "Glutes",
    secondary: ["Legs"],
    equipment: "Cable",
    pattern: "abduction",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Use a stable seated or standing position. Move the leg or knees outward against resistance, then return slowly.",
    ],
    cues: "Avoid rotating the pelvis or jerking the load.",
  },
  {
    id: "banded-lateral-walk",
    name: "Banded lateral walk",
    aliases: [],
    muscle: "Glutes",
    secondary: ["Legs"],
    equipment: "Band",
    pattern: "abduction",
    metric: "reps",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Use a stable seated or standing position. Move the leg or knees outward against resistance, then return slowly.",
    ],
    cues: "Avoid rotating the pelvis or jerking the load.",
  },
  {
    id: "standing-calf-raise",
    name: "Standing calf raise",
    aliases: [],
    muscle: "Calves",
    secondary: [],
    equipment: "Machine",
    pattern: "calf raise",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Support your balance and rise onto the balls of your feet. Pause, then lower your heels through a comfortable range.",
    ],
    cues: "Move through the ankles; avoid bouncing.",
  },
  {
    id: "seated-calf-raise",
    name: "Seated calf raise",
    aliases: [],
    muscle: "Calves",
    secondary: [],
    equipment: "Machine",
    pattern: "calf raise",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Support your balance and rise onto the balls of your feet. Pause, then lower your heels through a comfortable range.",
    ],
    cues: "Move through the ankles; avoid bouncing.",
  },
  {
    id: "leg-press-calf-raise",
    name: "Leg press calf raise",
    aliases: [],
    muscle: "Calves",
    secondary: [],
    equipment: "Machine",
    pattern: "calf raise",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Support your balance and rise onto the balls of your feet. Pause, then lower your heels through a comfortable range.",
    ],
    cues: "Move through the ankles; avoid bouncing.",
  },
  {
    id: "dumbbell-calf-raise",
    name: "Dumbbell calf raise",
    aliases: [],
    muscle: "Calves",
    secondary: [],
    equipment: "Dumbbell",
    pattern: "calf raise",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Support your balance and rise onto the balls of your feet. Pause, then lower your heels through a comfortable range.",
    ],
    cues: "Move through the ankles; avoid bouncing.",
  },
  {
    id: "bodyweight-calf-raise",
    name: "Bodyweight calf raise",
    aliases: [],
    muscle: "Calves",
    secondary: [],
    equipment: "Bodyweight",
    pattern: "calf raise",
    metric: "reps",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Support your balance and rise onto the balls of your feet. Pause, then lower your heels through a comfortable range.",
    ],
    cues: "Move through the ankles; avoid bouncing.",
  },
  {
    id: "seated-dumbbell-shoulder-press",
    name: "Seated dumbbell shoulder press",
    aliases: [],
    muscle: "Shoulders",
    secondary: ["Triceps"],
    equipment: "Dumbbell",
    pattern: "overhead press",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Start with the load at shoulder level. Brace your trunk and press overhead through a comfortable range, then lower slowly.",
    ],
    cues: "Keep ribs stacked; avoid excessive lower-back arch.",
  },
  {
    id: "standing-dumbbell-shoulder-press",
    name: "Standing dumbbell shoulder press",
    aliases: [],
    muscle: "Shoulders",
    secondary: ["Triceps"],
    equipment: "Dumbbell",
    pattern: "overhead press",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Start with the load at shoulder level. Brace your trunk and press overhead through a comfortable range, then lower slowly.",
    ],
    cues: "Keep ribs stacked; avoid excessive lower-back arch.",
  },
  {
    id: "barbell-overhead-press",
    name: "Barbell overhead press",
    aliases: [],
    muscle: "Shoulders",
    secondary: ["Triceps"],
    equipment: "Barbell",
    pattern: "overhead press",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Start with the load at shoulder level. Brace your trunk and press overhead through a comfortable range, then lower slowly.",
    ],
    cues: "Keep ribs stacked; avoid excessive lower-back arch.",
  },
  {
    id: "machine-shoulder-press",
    name: "Machine shoulder press",
    aliases: [],
    muscle: "Shoulders",
    secondary: ["Triceps"],
    equipment: "Machine",
    pattern: "overhead press",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Start with the load at shoulder level. Brace your trunk and press overhead through a comfortable range, then lower slowly.",
    ],
    cues: "Keep ribs stacked; avoid excessive lower-back arch.",
  },
  {
    id: "arnold-press",
    name: "Arnold press",
    aliases: [],
    muscle: "Shoulders",
    secondary: ["Triceps"],
    equipment: "Dumbbell",
    pattern: "overhead press",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Start with the load at shoulder level. Brace your trunk and press overhead through a comfortable range, then lower slowly.",
    ],
    cues: "Keep ribs stacked; avoid excessive lower-back arch.",
  },
  {
    id: "dumbbell-lateral-raise",
    name: "Dumbbell lateral raise",
    aliases: [],
    muscle: "Shoulders",
    secondary: ["Triceps"],
    equipment: "Dumbbell",
    pattern: "raise",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Keep a slight elbow bend and lift the arms through the intended plane without swinging. Return slowly.",
    ],
    cues: "Use a light load and stop at a comfortable height.",
  },
  {
    id: "cable-lateral-raise",
    name: "Cable lateral raise",
    aliases: [],
    muscle: "Shoulders",
    secondary: ["Triceps"],
    equipment: "Cable",
    pattern: "raise",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Keep a slight elbow bend and lift the arms through the intended plane without swinging. Return slowly.",
    ],
    cues: "Use a light load and stop at a comfortable height.",
  },
  {
    id: "machine-lateral-raise",
    name: "Machine lateral raise",
    aliases: [],
    muscle: "Shoulders",
    secondary: ["Triceps"],
    equipment: "Machine",
    pattern: "raise",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Keep a slight elbow bend and lift the arms through the intended plane without swinging. Return slowly.",
    ],
    cues: "Use a light load and stop at a comfortable height.",
  },
  {
    id: "dumbbell-front-raise",
    name: "Dumbbell front raise",
    aliases: [],
    muscle: "Shoulders",
    secondary: ["Triceps"],
    equipment: "Dumbbell",
    pattern: "raise",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Keep a slight elbow bend and lift the arms through the intended plane without swinging. Return slowly.",
    ],
    cues: "Use a light load and stop at a comfortable height.",
  },
  {
    id: "bent-over-reverse-fly",
    name: "Bent-over reverse fly",
    aliases: [],
    muscle: "Shoulders",
    secondary: ["Triceps"],
    equipment: "Dumbbell",
    pattern: "raise",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Keep a slight elbow bend and lift the arms through the intended plane without swinging. Return slowly.",
    ],
    cues: "Use a light load and stop at a comfortable height.",
  },
  {
    id: "reverse-pec-deck",
    name: "Reverse pec deck",
    aliases: [],
    muscle: "Shoulders",
    secondary: ["Triceps"],
    equipment: "Machine",
    pattern: "raise",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Keep a slight elbow bend and lift the arms through the intended plane without swinging. Return slowly.",
    ],
    cues: "Use a light load and stop at a comfortable height.",
  },
  {
    id: "cable-reverse-fly",
    name: "Cable reverse fly",
    aliases: [],
    muscle: "Shoulders",
    secondary: ["Triceps"],
    equipment: "Cable",
    pattern: "raise",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Keep a slight elbow bend and lift the arms through the intended plane without swinging. Return slowly.",
    ],
    cues: "Use a light load and stop at a comfortable height.",
  },
  {
    id: "cable-face-pull",
    name: "Cable face pull",
    aliases: [],
    muscle: "Shoulders",
    secondary: ["Triceps"],
    equipment: "Cable",
    pattern: "raise",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Keep a slight elbow bend and lift the arms through the intended plane without swinging. Return slowly.",
    ],
    cues: "Use a light load and stop at a comfortable height.",
  },
  {
    id: "dumbbell-curl",
    name: "Dumbbell curl",
    aliases: ["db curl"],
    muscle: "Biceps",
    secondary: [],
    equipment: "Dumbbell",
    pattern: "arm curl",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Keep your upper arms stable and bend your elbows to lift the resistance. Lower slowly through a comfortable range.",
    ],
    cues: "Avoid swinging or letting the wrists collapse.",
  },
  {
    id: "hammer-curl",
    name: "Hammer curl",
    aliases: [],
    muscle: "Biceps",
    secondary: [],
    equipment: "Dumbbell",
    pattern: "arm curl",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Keep your upper arms stable and bend your elbows to lift the resistance. Lower slowly through a comfortable range.",
    ],
    cues: "Avoid swinging or letting the wrists collapse.",
  },
  {
    id: "incline-dumbbell-curl",
    name: "Incline dumbbell curl",
    aliases: [],
    muscle: "Biceps",
    secondary: [],
    equipment: "Dumbbell",
    pattern: "arm curl",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Keep your upper arms stable and bend your elbows to lift the resistance. Lower slowly through a comfortable range.",
    ],
    cues: "Avoid swinging or letting the wrists collapse.",
  },
  {
    id: "concentration-curl",
    name: "Concentration curl",
    aliases: [],
    muscle: "Biceps",
    secondary: [],
    equipment: "Dumbbell",
    pattern: "arm curl",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Keep your upper arms stable and bend your elbows to lift the resistance. Lower slowly through a comfortable range.",
    ],
    cues: "Avoid swinging or letting the wrists collapse.",
  },
  {
    id: "barbell-curl",
    name: "Barbell curl",
    aliases: [],
    muscle: "Biceps",
    secondary: [],
    equipment: "Barbell",
    pattern: "arm curl",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Keep your upper arms stable and bend your elbows to lift the resistance. Lower slowly through a comfortable range.",
    ],
    cues: "Avoid swinging or letting the wrists collapse.",
  },
  {
    id: "ez-bar-curl",
    name: "EZ-bar curl",
    aliases: [],
    muscle: "Biceps",
    secondary: [],
    equipment: "Barbell",
    pattern: "arm curl",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Keep your upper arms stable and bend your elbows to lift the resistance. Lower slowly through a comfortable range.",
    ],
    cues: "Avoid swinging or letting the wrists collapse.",
  },
  {
    id: "cable-curl",
    name: "Cable curl",
    aliases: [],
    muscle: "Biceps",
    secondary: [],
    equipment: "Cable",
    pattern: "arm curl",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Keep your upper arms stable and bend your elbows to lift the resistance. Lower slowly through a comfortable range.",
    ],
    cues: "Avoid swinging or letting the wrists collapse.",
  },
  {
    id: "machine-preacher-curl",
    name: "Machine preacher curl",
    aliases: [],
    muscle: "Biceps",
    secondary: [],
    equipment: "Machine",
    pattern: "arm curl",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Keep your upper arms stable and bend your elbows to lift the resistance. Lower slowly through a comfortable range.",
    ],
    cues: "Avoid swinging or letting the wrists collapse.",
  },
  {
    id: "cable-triceps-pushdown",
    name: "Cable triceps pushdown",
    aliases: [],
    muscle: "Triceps",
    secondary: [],
    equipment: "Cable",
    pattern: "elbow extension",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Keep the upper arms stable and extend the elbows against resistance. Return under control.",
    ],
    cues: "Keep elbows comfortable and avoid forcing the end range.",
  },
  {
    id: "rope-triceps-pushdown",
    name: "Rope triceps pushdown",
    aliases: [],
    muscle: "Triceps",
    secondary: [],
    equipment: "Cable",
    pattern: "elbow extension",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Keep the upper arms stable and extend the elbows against resistance. Return under control.",
    ],
    cues: "Keep elbows comfortable and avoid forcing the end range.",
  },
  {
    id: "overhead-cable-triceps-extension",
    name: "Overhead cable triceps extension",
    aliases: [],
    muscle: "Triceps",
    secondary: [],
    equipment: "Cable",
    pattern: "elbow extension",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Keep the upper arms stable and extend the elbows against resistance. Return under control.",
    ],
    cues: "Keep elbows comfortable and avoid forcing the end range.",
  },
  {
    id: "dumbbell-overhead-triceps-extension",
    name: "Dumbbell overhead triceps extension",
    aliases: [],
    muscle: "Triceps",
    secondary: [],
    equipment: "Dumbbell",
    pattern: "elbow extension",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Keep the upper arms stable and extend the elbows against resistance. Return under control.",
    ],
    cues: "Keep elbows comfortable and avoid forcing the end range.",
  },
  {
    id: "dumbbell-skull-crusher",
    name: "Dumbbell skull crusher",
    aliases: [],
    muscle: "Triceps",
    secondary: [],
    equipment: "Dumbbell",
    pattern: "elbow extension",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Keep the upper arms stable and extend the elbows against resistance. Return under control.",
    ],
    cues: "Keep elbows comfortable and avoid forcing the end range.",
  },
  {
    id: "close-grip-bench-press",
    name: "Close-grip bench press",
    aliases: [],
    muscle: "Triceps",
    secondary: [],
    equipment: "Barbell",
    pattern: "elbow extension",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Keep the upper arms stable and extend the elbows against resistance. Return under control.",
    ],
    cues: "Keep elbows comfortable and avoid forcing the end range.",
  },
  {
    id: "plank",
    name: "Plank",
    aliases: [],
    muscle: "Core",
    secondary: [],
    equipment: "Bodyweight",
    pattern: "core",
    metric: "duration",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your abdomen and move or hold the position with control. Breathe steadily and stop when you cannot maintain position.",
    ],
    cues: "Avoid straining the neck or arching the lower back.",
  },
  {
    id: "side-plank",
    name: "Side plank",
    aliases: [],
    muscle: "Core",
    secondary: [],
    equipment: "Bodyweight",
    pattern: "core",
    metric: "duration",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your abdomen and move or hold the position with control. Breathe steadily and stop when you cannot maintain position.",
    ],
    cues: "Avoid straining the neck or arching the lower back.",
  },
  {
    id: "dead-bug",
    name: "Dead bug",
    aliases: [],
    muscle: "Core",
    secondary: [],
    equipment: "Bodyweight",
    pattern: "core",
    metric: "reps",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your abdomen and move or hold the position with control. Breathe steadily and stop when you cannot maintain position.",
    ],
    cues: "Avoid straining the neck or arching the lower back.",
  },
  {
    id: "bird-dog",
    name: "Bird dog",
    aliases: [],
    muscle: "Core",
    secondary: [],
    equipment: "Bodyweight",
    pattern: "core",
    metric: "reps",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your abdomen and move or hold the position with control. Breathe steadily and stop when you cannot maintain position.",
    ],
    cues: "Avoid straining the neck or arching the lower back.",
  },
  {
    id: "crunch",
    name: "Crunch",
    aliases: [],
    muscle: "Core",
    secondary: [],
    equipment: "Bodyweight",
    pattern: "core",
    metric: "reps",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your abdomen and move or hold the position with control. Breathe steadily and stop when you cannot maintain position.",
    ],
    cues: "Avoid straining the neck or arching the lower back.",
  },
  {
    id: "reverse-crunch",
    name: "Reverse crunch",
    aliases: [],
    muscle: "Core",
    secondary: [],
    equipment: "Bodyweight",
    pattern: "core",
    metric: "reps",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your abdomen and move or hold the position with control. Breathe steadily and stop when you cannot maintain position.",
    ],
    cues: "Avoid straining the neck or arching the lower back.",
  },
  {
    id: "hanging-knee-raise",
    name: "Hanging knee raise",
    aliases: [],
    muscle: "Core",
    secondary: [],
    equipment: "Bodyweight",
    pattern: "core",
    metric: "reps",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your abdomen and move or hold the position with control. Breathe steadily and stop when you cannot maintain position.",
    ],
    cues: "Avoid straining the neck or arching the lower back.",
  },
  {
    id: "cable-crunch",
    name: "Cable crunch",
    aliases: [],
    muscle: "Core",
    secondary: [],
    equipment: "Cable",
    pattern: "core",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your abdomen and move or hold the position with control. Breathe steadily and stop when you cannot maintain position.",
    ],
    cues: "Avoid straining the neck or arching the lower back.",
  },
  {
    id: "pallof-press",
    name: "Pallof press",
    aliases: [],
    muscle: "Core",
    secondary: [],
    equipment: "Cable",
    pattern: "core",
    metric: "reps",
    loaded: true,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Brace your abdomen and move or hold the position with control. Breathe steadily and stop when you cannot maintain position.",
    ],
    cues: "Avoid straining the neck or arching the lower back.",
  },
  {
    id: "treadmill-walk",
    name: "Treadmill walk",
    aliases: [],
    muscle: "Full body",
    secondary: [],
    equipment: "Cardio machine",
    pattern: "cardio",
    metric: "duration",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Begin at an easy pace and gradually settle into a sustainable effort. Slow down before finishing.",
    ],
    cues: "Choose a pace that matches your current fitness.",
  },
  {
    id: "treadmill-run",
    name: "Treadmill run",
    aliases: [],
    muscle: "Full body",
    secondary: [],
    equipment: "Cardio machine",
    pattern: "cardio",
    metric: "duration",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Begin at an easy pace and gradually settle into a sustainable effort. Slow down before finishing.",
    ],
    cues: "Choose a pace that matches your current fitness.",
  },
  {
    id: "stationary-bike",
    name: "Stationary bike",
    aliases: [],
    muscle: "Full body",
    secondary: [],
    equipment: "Cardio machine",
    pattern: "cardio",
    metric: "duration",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Begin at an easy pace and gradually settle into a sustainable effort. Slow down before finishing.",
    ],
    cues: "Choose a pace that matches your current fitness.",
  },
  {
    id: "elliptical",
    name: "Elliptical",
    aliases: [],
    muscle: "Full body",
    secondary: [],
    equipment: "Cardio machine",
    pattern: "cardio",
    metric: "duration",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Begin at an easy pace and gradually settle into a sustainable effort. Slow down before finishing.",
    ],
    cues: "Choose a pace that matches your current fitness.",
  },
  {
    id: "rowing-ergometer",
    name: "Rowing ergometer",
    aliases: [],
    muscle: "Full body",
    secondary: [],
    equipment: "Cardio machine",
    pattern: "cardio",
    metric: "duration",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Begin at an easy pace and gradually settle into a sustainable effort. Slow down before finishing.",
    ],
    cues: "Choose a pace that matches your current fitness.",
  },
  {
    id: "stair-climber",
    name: "Stair climber",
    aliases: [],
    muscle: "Full body",
    secondary: [],
    equipment: "Cardio machine",
    pattern: "cardio",
    metric: "duration",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Begin at an easy pace and gradually settle into a sustainable effort. Slow down before finishing.",
    ],
    cues: "Choose a pace that matches your current fitness.",
  },
  {
    id: "outdoor-walk",
    name: "Outdoor walk",
    aliases: [],
    muscle: "Full body",
    secondary: [],
    equipment: "None",
    pattern: "cardio",
    metric: "distance",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Begin at an easy pace and gradually settle into a sustainable effort. Slow down before finishing.",
    ],
    cues: "Choose a pace that matches your current fitness.",
  },
  {
    id: "outdoor-run",
    name: "Outdoor run",
    aliases: [],
    muscle: "Full body",
    secondary: [],
    equipment: "None",
    pattern: "cardio",
    metric: "distance",
    loaded: false,
    instructions: [
      "Set up the equipment securely and select an appropriate resistance.",
      "Begin at an easy pace and gradually settle into a sustainable effort. Slow down before finishing.",
    ],
    cues: "Choose a pace that matches your current fitness.",
  },
];
export const equipmentOptions = [
  ...new Set(catalog.map((e) => e.equipment)),
].sort();
export const muscles = [...new Set(catalog.map((e) => e.muscle))].sort();
// Movement-specific cues supplement the shared setup instructions.
const specificInstructions: Record<string, string> = {
  "Cable face pull":
    "Set a rope near face height. Pull toward the face with elbows out, then return slowly without leaning back.",
  "Close-grip bench press":
    "Lie on a bench with the bar gripped slightly narrower than a standard press. Lower toward the chest with controlled elbows, then press up. Use safety stops or a spotter.",
  "Straight-arm cable pulldown":
    "Stand at a high pulley. Keep a slight fixed elbow bend and draw the handle toward your thighs. Return slowly without swinging.",
  "Arnold press":
    "Begin with dumbbells at the shoulders, palms toward you. Rotate palms forward as you press overhead and reverse slowly within a comfortable range.",
  "Pendlay row":
    "Hinge with a braced torso and row the bar from the floor toward the lower chest. Set the bar down between repetitions without rounding or jerking.",
  Plank:
    "Support yourself on forearms and toes. Hold a braced, straight body position while breathing. Stop when your position cannot be maintained.",
  "Side plank":
    "Lie on your side with the elbow under the shoulder. Raise your hips and hold a straight supported position. Repeat on the other side; bend the knees to shorten the lever if needed.",
  "Dead bug":
    "Lie on your back with arms up and hips and knees bent. Slowly extend one arm and the opposite leg, return, and alternate without arching your back.",
  "Bird dog":
    "From hands and knees, extend one arm and the opposite leg. Return and alternate without rotating the trunk or arching the back.",
  Crunch:
    "Lie on your back with knees bent. Lift the shoulder blades slightly while drawing the ribs toward the pelvis. Lower without pulling on your neck.",
  "Reverse crunch":
    "Lie on your back with knees bent. Curl the pelvis toward the ribs, then lower slowly without swinging the legs.",
  "Hanging knee raise":
    "Hang securely from a bar or supported station. Bring bent knees toward your torso without swinging, then lower slowly.",
  "Cable crunch":
    "Kneel at a high rope pulley with the rope near your head. Draw the ribs toward the pelvis by flexing your trunk. Return under control; keep the arms relatively fixed.",
  "Pallof press":
    "Stand sideways to a pulley with the handle at your chest. Press it forward and resist rotation, then return. Repeat on both sides with a stable stance.",
  "Banded lateral walk":
    "Place a resistance loop above the knees or around the ankles. Maintain slight hip and knee flexion and take controlled side steps without swaying.",
  "Cable glute kickback":
    "Secure an ankle cuff to a low pulley and hold a stable support. Extend the leg behind you, then return slowly without arching the back.",
  "Rowing ergometer":
    "Push through the legs, open the hips, then draw the handle to the lower ribs. Return arms first, hinge forward, then bend the knees. Start at an easy effort.",
};
for (const exercise of catalog)
  if (specificInstructions[exercise.name])
    exercise.instructions = [
      exercise.instructions[0],
      specificInstructions[exercise.name],
    ];
const closeGrip = catalog.find((e) => e.name === "Close-grip bench press")!;
closeGrip.pattern = "press";
closeGrip.secondary = ["Chest", "Shoulders"];

// A position-neutral press for logs that do not specify seated or standing.
catalog.push({
  id: "dumbbell-shoulder-press",
  name: "Dumbbell shoulder press",
  aliases: ["DB shoulder press"],
  muscle: "Shoulders",
  secondary: ["Triceps"],
  equipment: "Dumbbell",
  pattern: "overhead press",
  metric: "reps",
  loaded: true,
  instructions: [
    "Use a stable seated or standing position with dumbbells at shoulder level.",
    "Brace your trunk, press overhead through a comfortable range, then lower under control.",
  ],
  cues: "Keep ribs stacked and avoid arching the lower back.",
});
