-- iTry V1 schema. Apply to a dedicated iTry Supabase project.
create table if not exists public.itry_profiles(id uuid primary key references auth.users(id) on delete cascade,display_name text not null,learning_enabled boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.itry_connections(id uuid primary key default gen_random_uuid(),requester_id uuid not null references auth.users(id),recipient_id uuid not null references auth.users(id),status text not null check(status in('pending','accepted','removed','blocked')),created_at timestamptz not null default now(),unique(requester_id,recipient_id));
create table if not exists public.itry_connection_preferences(id uuid primary key default gen_random_uuid(),owner_user_id uuid not null references auth.users(id),connection_id uuid not null references public.itry_connections(id) on delete cascade,relationship_label text,budget_min numeric,budget_max numeric,autopilot_enabled boolean not null default false,autopilot_max numeric,veto_window_hours int not null default 24,unique(owner_user_id,connection_id));
create table if not exists public.itry_occasions(id uuid primary key default gen_random_uuid(),owner_user_id uuid not null references auth.users(id),subject_user_id uuid references auth.users(id),title text not null,occasion_type text not null,event_date date not null,recurs_annually boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.itry_preference_signals(id uuid primary key default gen_random_uuid(),subject_user_id uuid not null references auth.users(id),signal_type text not null,topic text not null,confidence numeric not null default .5 check(confidence between 0 and 1),source text not null,created_at timestamptz not null default now());
create table if not exists public.itry_delivery_profiles(id uuid primary key default gen_random_uuid(),owner_user_id uuid not null unique references auth.users(id),label text not null default 'Preferred address',address_payload jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.itry_gift_intents(id uuid primary key default gen_random_uuid(),giver_id uuid not null references auth.users(id),recipient_id uuid not null references auth.users(id),occasion_id uuid references public.itry_occasions(id),item_ref text not null,status text not null default 'candidate',price numeric,created_at timestamptz not null default now());

alter table public.itry_profiles enable row level security;alter table public.itry_connections enable row level security;alter table public.itry_connection_preferences enable row level security;alter table public.itry_occasions enable row level security;alter table public.itry_preference_signals enable row level security;alter table public.itry_delivery_profiles enable row level security;alter table public.itry_gift_intents enable row level security;

grant select,insert,update,delete on public.itry_profiles,public.itry_connections,public.itry_connection_preferences,public.itry_occasions,public.itry_preference_signals,public.itry_delivery_profiles,public.itry_gift_intents to authenticated;

create policy itry_profiles_self on public.itry_profiles for all to authenticated using((select auth.uid())=id) with check((select auth.uid())=id);
create policy itry_connections_read_participant on public.itry_connections for select to authenticated using((select auth.uid())=requester_id or (select auth.uid())=recipient_id);
create policy itry_connections_create_self on public.itry_connections for insert to authenticated with check((select auth.uid())=requester_id);
create policy itry_connections_update_participant on public.itry_connections for update to authenticated using((select auth.uid())=requester_id or (select auth.uid())=recipient_id) with check((select auth.uid())=requester_id or (select auth.uid())=recipient_id);
create policy itry_connection_preferences_owner on public.itry_connection_preferences for all to authenticated using((select auth.uid())=owner_user_id) with check((select auth.uid())=owner_user_id);
create policy itry_occasions_owner on public.itry_occasions for all to authenticated using((select auth.uid())=owner_user_id) with check((select auth.uid())=owner_user_id);
create policy itry_preference_signals_subject on public.itry_preference_signals for all to authenticated using((select auth.uid())=subject_user_id) with check((select auth.uid())=subject_user_id);
create policy itry_delivery_profiles_owner on public.itry_delivery_profiles for all to authenticated using((select auth.uid())=owner_user_id) with check((select auth.uid())=owner_user_id);
create policy itry_gift_intents_giver on public.itry_gift_intents for all to authenticated using((select auth.uid())=giver_id) with check((select auth.uid())=giver_id);
